/*1) CLIENTE = {CODCLIENTE, NOMECLIENTE, FOTO, DATANASC, CODSEXO_FK, CODRUA_FK,
CODBAIRRO_FK, CODCEP_FK, CODCIDADE_FK, SALARIO, CODTRABALHO_FK, NUMEROCASA_FK}*/
CREATE TABLE CLIENTE
CODCLIENTE SERIAL PRIMARY KEY,
NOMECLIENTE VARCHAR(80) NOT NULL,
FOTO VARBINARY(MAX) NOT NULL UNIQUE,
DATANASC VARCHAR(80) NOT NULL,
CODSEXO_FK INTEGER REFERENCES SEXO(CODSEXO) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
CODRUA_FK INTEGER REFERENCES RUA(CODRUA) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
CODBAIRRO_FK INTEGER REFERENCES BAIRRO(CODBAIRRO) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
CODCEP_FK INTEGER REFERENCES CEP(CODCEP) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
CODCIDADE_FK INTEGER REFERENCES CIDADE(CODCIDADE) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
SALARIO NUMERIC (10,2) NOT NULL,
CODTRABALHO_FK INTEGER REFERENCES TRABALHO(CODTRABALHO) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
NUMEROCASA_FK INTEGER REFERENCES FUNCIONARIOS(NUMEROCASA) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE


--2) SEXO = {CODSEXO, NOMESEXO}
CREATE TABLE SEXO
CODSEXO SERIAL PRIMARY KEY,
NOMESEXO VARCHAR (9) NOT NULL UNIQUE

--3) RUA = {CODRUA, NOMERUA}
CREATE TABLE RUA
CODRUA SERIAL PRIMARY KEY,
NOMERUA VARCHAR (80) NOT NULL UNIQUE

--4) BAIRRO = {CODBAIRRO, NOMEBAIRRO}
CREATE TABLE BAIRRO
CODBAIRRO SERIAL PRIMARY KEY,
NOMEBAIRRO VARCHAR (80) NOT NULL UNIQUE

--5) CEP = {CODCEP, NUMEROCEP}
CREATE TABLE CEP
CODCEP SERIAL PRIMARY KEY,
NUMEROCEP CHAR(9) NOT NULL UNIQUE

--6) CIDADE = {CODCIDADE, NOMECIDADE, CODUF}
CREATE TABLE CIDADE
CODCIDADE SERIAL PRIMARY KEY,
NOMECIDADE VARCHAR(80) NOT NULL UNIQUE,
CODUF INTEGER(2) NOT NULL UNIQUE

--7) UF = {CODUF, NOMEUF, SIGLA}
CREATE TABLE UF
CODUF_FK INTEGER REFERENCES CIDADE(CODUF) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
NOMEUF VARCHAR (80) NOT NULL UNIQUE,
SIGLA CHAR (2) NOT NULL UNIQUE

--8) TRABALHO = {CODTRABALHO, NOMETRABALHO}
CREATE TABLE TRABALHO
CODTRABALHO SERIAL PRIMARY KEY,
NOMETRABALHO VARCHAR(80) NOT NULL

--9) TELEFONE = {CODTELEFONE, NUMERO, CODOPERADORA}
CREATE TABLE TELEFONE
CODTELEFONE SERIAL PRIMARY KEY,
NUMERO CHAR (9) NOT NULL UNIQUE,
CODOPERADORA_FK INTEGER REFERENCES OPERADORA(CODOPERADORA) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE

--10) OPERADORA = {CODPERADORA, NOMEOPERADORA}
CREATE TABLE OPERADORA
CODOPERADORA SERIAL PRIMARY KEY,
NOMEOPERADORA VARCHAR(80) NOT NULL UNIQUE

--11) ITENSTELCLIENTE = {CODTELEFONE, CODCLIENTE}
CREATE TABLE ITENSTELCLIENTE
CODTELEFONE_FK INTEGER REFERENCES TELEFONE(CODTELEFONE) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
CODCLIENTE_FK INTEGER REFERENCES CLIENTE(CODCLIENTE) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,

--12) ITENSTELEFONETRABALHO = {CODTRABALHO, CODTELEFONE}
CREATE TABLE ITENSTELEFONETRABALHO
CODTRABALHO_FK INTEGER REFERENCES TRABALHO(CODTRABALHO) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,


/*13) FUNCIONARIOS = {CODFUNCIONARIO, NOMEFUNCIONARIO, NUMEROCASA,
14) CODRUA, CODBAIRRO, CODCEP, CODCIDADE, CODFUNCAO, SALARIO, CODLOJA}*/
--15) FUNCAO = {CODFUNCAO, NOMEFUNCAO}
--16) ITENSTELEFONEFUNCIONARIO = {CODFUNCIONARIO, CODTELEFONE}
--17) LOGIN = {CODLOGIN, USUARIO, SENHA, CODFUNCIONARIO}
--18) CONTROLELOGSISTEMA = {CODCONTROLE, CODLOGIN, DATA, HORA}
--19) ACESSO = {CODACESSO, NOMEACESSO}
--20) ITENSACESSOLOGIN = {CODACESSO, CODLOGIN}
--21) LOJA = {CODLOJA, NOMELOJA, CNPJ, NOMEFANTASIA, RAZAOSOCIAL}
--22) ITENSTELEFONELOJA={CODLOJA, CODTELEFONE}
/*23) PRODUTO = {CODPRODUTO, NOMEPRODUTO, QUANTIDADE, VALOR, CODMARCA,
CODTIPO }*/
--24) MARCA={CODMARCA, NOMEMARCA}
--25) TIPO={CODTIPO, NOMETIPO}
/*26) FORNECEDOR={CODFORNECEDOR, NOMEFORNECEDOR, NUMEROCASA, CORUA,
CODBAIRRO, CODCEP, CODCIDADE}*/
--27) ITENSTELEFONEFORNECEDOR={CODTELEFONE, CODFORNECEDOR}
/*28) COMPRAPRODUTO = {CODCOMPRA, DATACOMPRA, CODFORNECEDOR,
CODFUNCIONARIO}*/
--29) ITENSCOMPRAPRODUTO = {CODCOMPRA, CODPRODUTO, QUANTIDADE, VALORC}
/*30) PARCELACOMPRA = {CODPARCELACOMPRA, DATAVENCIMENTO, VALOR,
CODSITUACAO, CODCOMPRA}*/
--31) SITUACAO = {CODSITUACAO, NOMESITUACAO}
--32) VENDAPRODUTO = {CODVENDA, DATAVENDA, CODCLIENTE, CODFUNCIONARIO}
--33) ITENSVENDAPRODUTO = {CODVENDA,CODPRODUTO, QUANTIDADE, VALOR}
/*34) PARCELAVENDA={CODPARCELA, DATAVENCIMENTO, VALOR, CODSITUACAO,
CODVENDA}*/
--35) IMAGENS={CODIMAGENS, IMAGEM, DESCRICAO, CODPRODUTO}